[tool.poetry]
name = "japanese_voice_alerts"
version = "0.1.0"
description = ""
authors = ["nojio"]

[tool.poetry.dependencies]
python = "^3.9"
pydub = "^0.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
